### ISSUE TITLE
What to do next?

### ISSUE THREAD

**Issue by Bitmona** [VectorLogoZone/awesome-emoji#1]
So i was told this is my project i don't see anything clear that needs to be done?

**Comment by fileformat** [comment]
I just added a script "bin/update-noto.py" that does what I want for the Noto emoji collection.  I want a similar script for the other collections.  You can use the noto one as a starter.

**Comment by Bitmona** [comment]
ok

**Comment by Crissov** [comment]
You will probably want to have a look at https://github.com/iamcal/emoji-data/
